parameters:
  pool: 'Hosted VS2017'
  jobName: 'win_packaging'
  parentJobs: []

jobs:
- job: ${{ parameters.jobName }}
  dependsOn:
      ${{ parameters.parentJobs }}
  pool:
    name: ${{ parameters.pool }}

  displayName: Windows Packaging

  steps:
  - pwsh: |
      Get-ChildItem -Path env:
    displayName: Capture environment
    condition: succeededOrFailed()

  - template: /tools/releaseBuild/azureDevOps/templates/insert-nuget-config-azfeed.yml

  - pwsh: |
      Import-Module .\tools\ci.psm1
      Invoke-CIInstall
    displayName: Bootstrap
    condition: succeededOrFailed()

  - pwsh: |
      Import-Module .\tools\ci.psm1
      New-CodeCoverageAndTestPackage
      Invoke-CIFinish
    displayName: Build and Test Package
