parameters:
  pool: 'Hosted VS2017'
  jobName: 'win_packaging'
  parentJobs: []

jobs:
- job: ${{ parameters.jobName }}
  dependsOn:
      ${{ parameters.parentJobs }}
  pool:
    name: ${{ parameters.pool }}

  displayName: Windows Packaging

  steps:
  - powershell: |
      Get-ChildItem -Path env:
    displayName: Capture environment
    condition: succeededOrFailed()

  - template: /tools/releaseBuild/azureDevOps/templates/insert-nuget-config-azfeed.yml

  - powershell: |
      [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
      Import-Module .\tools\ci.psm1
      Invoke-CIInstall
    displayName: Bootstrap
    condition: succeededOrFailed()

  - task: PowerShell@1
    displayName: Build and Test Package
    inputs:
      scriptType: inlineScript
      arguments: '$(NUGET_KEY)'
      inlineScript: |
        Param($NuGetKey)
        Invoke-CIFinish -NuGetKey $NuGetKey
